language: go
go:
- 1.x
deploy:
  provider: releases
  api_key:
    secure: u+ZCN5GoEmN/JcG4rC5ioxoTGZ3wWHF4atS6scevqhv0EbHzfsnmxvX+mx0pGDPIVxfifeGafTkVckT3lbDYMeIAM+qyT4DJuF8R3gHpU9G+3rGCtfuBmKoCGjy+mpAPVLhxDXSvbZV4VSxhs45rS3UgBKo+icM6jSYiJht/8GLQrBLlq7592tSew6jEbaQLGi0UY/JoQX83Th4RzQa9RExTE54AVA6W6pHQP+hY8xi5zKn/PU1gSMqISUTeq1DDebnJX/qMqSZdPx9yT9ddI69SFtdTghDAscXWKIpu31NNZk/1b25sA5ZE5ytvrrlizcZAgCBxZJfMHlfxyl8lO68B5Zd0jH8meD1u561KrrtiuyDHrfBWt6qvUUmo1ztpZky5AoDozbPnS/8BBYELE8q5xyVoBgevYXGlGffRF4HsEsKKTbjuatbMO4Gkhy/apGlgxnZ+qlx2TFdEfOT97OMT12VSeZWqpvYisdFbsKHRdZOax8+UapE8jV7jlKgMZS5Io98jNsmxjHRrqDTgr7VEDfQMhOBIq+pnjj5UqR6BCFFagD5a7hBAZP+PmcbTWpRbTFeO/H8E9hAXy9JPybwRvcZ579s1dJ0DWUzeYHluccwu51tQ+H0lxq/QC7G88v7BLVUFf3HLJz7nlPEjtVT0wkmq33R2oDuE1opul2k=
  file: bin/chrome-ssh-agent.zip
  skip_cleanup: true
  on:
    tags: true
